// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../work/nazgul/copyrepo/copyrepo-web-api/src/main/resources/models"
)

// GetCopyInstancesOKCode is the HTTP code returned for type GetCopyInstancesOK
const GetCopyInstancesOKCode int = 200

/*GetCopyInstancesOK Successfully listed copy instances managed by crb

swagger:response getCopyInstancesOK
*/
type GetCopyInstancesOK struct {

	/*copyId is currently used to access CopyInstance.
	  In: Body
	*/
	Payload []*models.CopyInstance `json:"body,omitempty"`
}

// NewGetCopyInstancesOK creates GetCopyInstancesOK with default headers values
func NewGetCopyInstancesOK() *GetCopyInstancesOK {
	return &GetCopyInstancesOK{}
}

// WithPayload adds the payload to the get copy instances o k response
func (o *GetCopyInstancesOK) WithPayload(payload []*models.CopyInstance) *GetCopyInstancesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get copy instances o k response
func (o *GetCopyInstancesOK) SetPayload(payload []*models.CopyInstance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCopyInstancesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.CopyInstance, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetCopyInstancesNoContentCode is the HTTP code returned for type GetCopyInstancesNoContent
const GetCopyInstancesNoContentCode int = 204

/*GetCopyInstancesNoContent Operation succeeded; however, currently no copies are managed by crb

swagger:response getCopyInstancesNoContent
*/
type GetCopyInstancesNoContent struct {
}

// NewGetCopyInstancesNoContent creates GetCopyInstancesNoContent with default headers values
func NewGetCopyInstancesNoContent() *GetCopyInstancesNoContent {
	return &GetCopyInstancesNoContent{}
}

// WriteResponse to the client
func (o *GetCopyInstancesNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// GetCopyInstancesInternalServerErrorCode is the HTTP code returned for type GetCopyInstancesInternalServerError
const GetCopyInstancesInternalServerErrorCode int = 500

/*GetCopyInstancesInternalServerError Internal error -- Most likely Metadata-DB could not be accessed

swagger:response getCopyInstancesInternalServerError
*/
type GetCopyInstancesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCopyInstancesInternalServerError creates GetCopyInstancesInternalServerError with default headers values
func NewGetCopyInstancesInternalServerError() *GetCopyInstancesInternalServerError {
	return &GetCopyInstancesInternalServerError{}
}

// WithPayload adds the payload to the get copy instances internal server error response
func (o *GetCopyInstancesInternalServerError) WithPayload(payload *models.Error) *GetCopyInstancesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get copy instances internal server error response
func (o *GetCopyInstancesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCopyInstancesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetCopyInstancesDefault Unexpected error

swagger:response getCopyInstancesDefault
*/
type GetCopyInstancesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCopyInstancesDefault creates GetCopyInstancesDefault with default headers values
func NewGetCopyInstancesDefault(code int) *GetCopyInstancesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCopyInstancesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get copy instances default response
func (o *GetCopyInstancesDefault) WithStatusCode(code int) *GetCopyInstancesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get copy instances default response
func (o *GetCopyInstancesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get copy instances default response
func (o *GetCopyInstancesDefault) WithPayload(payload *models.Error) *GetCopyInstancesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get copy instances default response
func (o *GetCopyInstancesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCopyInstancesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
