// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCopyInstancesParams creates a new GetCopyInstancesParams object
// with the default values initialized.
func NewGetCopyInstancesParams() GetCopyInstancesParams {
	var ()
	return GetCopyInstancesParams{}
}

// GetCopyInstancesParams contains all the bound params for the get copy instances operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCopyInstances
type GetCopyInstancesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*page number of paginated list. e.g. copies list
	  In: query
	*/
	PageNumber *int32
	/*page size of paginated list. e.g. copies list
	  In: query
	*/
	PageSize *int32
	/*The id of the copy repository instance
	  In: query
	*/
	RepoIDInQuery *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetCopyInstancesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPageNumber, qhkPageNumber, _ := qs.GetOK("pageNumber")
	if err := o.bindPageNumber(qPageNumber, qhkPageNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	qPageSize, qhkPageSize, _ := qs.GetOK("pageSize")
	if err := o.bindPageSize(qPageSize, qhkPageSize, route.Formats); err != nil {
		res = append(res, err)
	}

	qRepoIDInQuery, qhkRepoIDInQuery, _ := qs.GetOK("repoIdInQuery")
	if err := o.bindRepoIDInQuery(qRepoIDInQuery, qhkRepoIDInQuery, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCopyInstancesParams) bindPageNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("pageNumber", "query", "int32", raw)
	}
	o.PageNumber = &value

	return nil
}

func (o *GetCopyInstancesParams) bindPageSize(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("pageSize", "query", "int32", raw)
	}
	o.PageSize = &value

	return nil
}

func (o *GetCopyInstancesParams) bindRepoIDInQuery(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.RepoIDInQuery = &raw

	return nil
}
