// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../work/nazgul/copyrepo/copyrepo-web-api/src/main/resources/models"
)

// GetCopyMetaDataOKCode is the HTTP code returned for type GetCopyMetaDataOK
const GetCopyMetaDataOKCode int = 200

/*GetCopyMetaDataOK Successfully returned copy instance attributes

swagger:response getCopyMetaDataOK
*/
type GetCopyMetaDataOK struct {

	/*
	  In: Body
	*/
	Payload *models.CopyMetaData `json:"body,omitempty"`
}

// NewGetCopyMetaDataOK creates GetCopyMetaDataOK with default headers values
func NewGetCopyMetaDataOK() *GetCopyMetaDataOK {
	return &GetCopyMetaDataOK{}
}

// WithPayload adds the payload to the get copy meta data o k response
func (o *GetCopyMetaDataOK) WithPayload(payload *models.CopyMetaData) *GetCopyMetaDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get copy meta data o k response
func (o *GetCopyMetaDataOK) SetPayload(payload *models.CopyMetaData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCopyMetaDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCopyMetaDataNotFoundCode is the HTTP code returned for type GetCopyMetaDataNotFound
const GetCopyMetaDataNotFoundCode int = 404

/*GetCopyMetaDataNotFound Copy instance of specified copyId does not exist

swagger:response getCopyMetaDataNotFound
*/
type GetCopyMetaDataNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCopyMetaDataNotFound creates GetCopyMetaDataNotFound with default headers values
func NewGetCopyMetaDataNotFound() *GetCopyMetaDataNotFound {
	return &GetCopyMetaDataNotFound{}
}

// WithPayload adds the payload to the get copy meta data not found response
func (o *GetCopyMetaDataNotFound) WithPayload(payload *models.Error) *GetCopyMetaDataNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get copy meta data not found response
func (o *GetCopyMetaDataNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCopyMetaDataNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCopyMetaDataInternalServerErrorCode is the HTTP code returned for type GetCopyMetaDataInternalServerError
const GetCopyMetaDataInternalServerErrorCode int = 500

/*GetCopyMetaDataInternalServerError Internal error -- Most likely Metadata-DB could not be accessed

swagger:response getCopyMetaDataInternalServerError
*/
type GetCopyMetaDataInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCopyMetaDataInternalServerError creates GetCopyMetaDataInternalServerError with default headers values
func NewGetCopyMetaDataInternalServerError() *GetCopyMetaDataInternalServerError {
	return &GetCopyMetaDataInternalServerError{}
}

// WithPayload adds the payload to the get copy meta data internal server error response
func (o *GetCopyMetaDataInternalServerError) WithPayload(payload *models.Error) *GetCopyMetaDataInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get copy meta data internal server error response
func (o *GetCopyMetaDataInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCopyMetaDataInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetCopyMetaDataDefault unexpected error

swagger:response getCopyMetaDataDefault
*/
type GetCopyMetaDataDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCopyMetaDataDefault creates GetCopyMetaDataDefault with default headers values
func NewGetCopyMetaDataDefault(code int) *GetCopyMetaDataDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCopyMetaDataDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get copy meta data default response
func (o *GetCopyMetaDataDefault) WithStatusCode(code int) *GetCopyMetaDataDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get copy meta data default response
func (o *GetCopyMetaDataDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get copy meta data default response
func (o *GetCopyMetaDataDefault) WithPayload(payload *models.Error) *GetCopyMetaDataDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get copy meta data default response
func (o *GetCopyMetaDataDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCopyMetaDataDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
