// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoryInfoParams creates a new GetRepositoryInfoParams object
// with the default values initialized.
func NewGetRepositoryInfoParams() GetRepositoryInfoParams {
	var ()
	return GetRepositoryInfoParams{}
}

// GetRepositoryInfoParams contains all the bound params for the get repository info operation
// typically these are obtained from a http.Request
//
// swagger:parameters getRepositoryInfo
type GetRepositoryInfoParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The id of the copy repository instance
	  Required: true
	  In: path
	*/
	RepoID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetRepositoryInfoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rRepoID, rhkRepoID, _ := route.Params.GetOK("repoId")
	if err := o.bindRepoID(rRepoID, rhkRepoID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetRepositoryInfoParams) bindRepoID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.RepoID = raw

	return nil
}
