// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListRepositoryInstancesParams creates a new ListRepositoryInstancesParams object
// with the default values initialized.
func NewListRepositoryInstancesParams() ListRepositoryInstancesParams {
	var ()
	return ListRepositoryInstancesParams{}
}

// ListRepositoryInstancesParams contains all the bound params for the list repository instances operation
// typically these are obtained from a http.Request
//
// swagger:parameters listRepositoryInstances
type ListRepositoryInstancesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ListRepositoryInstancesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
