// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../work/nazgul/copyrepo/copyrepo-web-api/src/main/resources/models"
)

// StoreCopyMetaDataCreatedCode is the HTTP code returned for type StoreCopyMetaDataCreated
const StoreCopyMetaDataCreatedCode int = 201

/*StoreCopyMetaDataCreated Successfully stored copy instance attributes

swagger:response storeCopyMetaDataCreated
*/
type StoreCopyMetaDataCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CopyInstance `json:"body,omitempty"`
}

// NewStoreCopyMetaDataCreated creates StoreCopyMetaDataCreated with default headers values
func NewStoreCopyMetaDataCreated() *StoreCopyMetaDataCreated {
	return &StoreCopyMetaDataCreated{}
}

// WithPayload adds the payload to the store copy meta data created response
func (o *StoreCopyMetaDataCreated) WithPayload(payload *models.CopyInstance) *StoreCopyMetaDataCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the store copy meta data created response
func (o *StoreCopyMetaDataCreated) SetPayload(payload *models.CopyInstance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StoreCopyMetaDataCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StoreCopyMetaDataConflictCode is the HTTP code returned for type StoreCopyMetaDataConflict
const StoreCopyMetaDataConflictCode int = 409

/*StoreCopyMetaDataConflict A copy instance with the same copyId exists. Either use different copyId or delete existing copyId instance before retrying

swagger:response storeCopyMetaDataConflict
*/
type StoreCopyMetaDataConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStoreCopyMetaDataConflict creates StoreCopyMetaDataConflict with default headers values
func NewStoreCopyMetaDataConflict() *StoreCopyMetaDataConflict {
	return &StoreCopyMetaDataConflict{}
}

// WithPayload adds the payload to the store copy meta data conflict response
func (o *StoreCopyMetaDataConflict) WithPayload(payload *models.Error) *StoreCopyMetaDataConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the store copy meta data conflict response
func (o *StoreCopyMetaDataConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StoreCopyMetaDataConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StoreCopyMetaDataInternalServerErrorCode is the HTTP code returned for type StoreCopyMetaDataInternalServerError
const StoreCopyMetaDataInternalServerErrorCode int = 500

/*StoreCopyMetaDataInternalServerError Internal error -- Most likely Metadata-DB could not be accessed

swagger:response storeCopyMetaDataInternalServerError
*/
type StoreCopyMetaDataInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStoreCopyMetaDataInternalServerError creates StoreCopyMetaDataInternalServerError with default headers values
func NewStoreCopyMetaDataInternalServerError() *StoreCopyMetaDataInternalServerError {
	return &StoreCopyMetaDataInternalServerError{}
}

// WithPayload adds the payload to the store copy meta data internal server error response
func (o *StoreCopyMetaDataInternalServerError) WithPayload(payload *models.Error) *StoreCopyMetaDataInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the store copy meta data internal server error response
func (o *StoreCopyMetaDataInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StoreCopyMetaDataInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*StoreCopyMetaDataDefault unexpected error

swagger:response storeCopyMetaDataDefault
*/
type StoreCopyMetaDataDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStoreCopyMetaDataDefault creates StoreCopyMetaDataDefault with default headers values
func NewStoreCopyMetaDataDefault(code int) *StoreCopyMetaDataDefault {
	if code <= 0 {
		code = 500
	}

	return &StoreCopyMetaDataDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the store copy meta data default response
func (o *StoreCopyMetaDataDefault) WithStatusCode(code int) *StoreCopyMetaDataDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the store copy meta data default response
func (o *StoreCopyMetaDataDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the store copy meta data default response
func (o *StoreCopyMetaDataDefault) WithPayload(payload *models.Error) *StoreCopyMetaDataDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the store copy meta data default response
func (o *StoreCopyMetaDataDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StoreCopyMetaDataDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
