// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"../../work/nazgul/copyrepo/copyrepo-web-api/src/main/resources/models"
)

// NewStoreCopyMetaDataParams creates a new StoreCopyMetaDataParams object
// with the default values initialized.
func NewStoreCopyMetaDataParams() StoreCopyMetaDataParams {
	var ()
	return StoreCopyMetaDataParams{}
}

// StoreCopyMetaDataParams contains all the bound params for the store copy meta data operation
// typically these are obtained from a http.Request
//
// swagger:parameters storeCopyMetaData
type StoreCopyMetaDataParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The id of the copy instance.
	  Required: true
	  In: path
	*/
	CopyID string
	/*copy metadata
	  Required: true
	  In: body
	*/
	CopyMeta *models.CopyMetaData
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *StoreCopyMetaDataParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rCopyID, rhkCopyID, _ := route.Params.GetOK("copyId")
	if err := o.bindCopyID(rCopyID, rhkCopyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CopyMetaData
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("copyMeta", "body"))
			} else {
				res = append(res, errors.NewParseError("copyMeta", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CopyMeta = &body
			}
		}

	} else {
		res = append(res, errors.Required("copyMeta", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StoreCopyMetaDataParams) bindCopyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.CopyID = raw

	return nil
}
