// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"../../work/nazgul/copyrepo/copyrepo-web-api/src/main/resources/models"
)

// NewCreateCopyInRepoParams creates a new CreateCopyInRepoParams object
// with the default values initialized.
func NewCreateCopyInRepoParams() CreateCopyInRepoParams {
	var ()
	return CreateCopyInRepoParams{}
}

// CreateCopyInRepoParams contains all the bound params for the create copy in repo operation
// typically these are obtained from a http.Request
//
// swagger:parameters createCopyInRepo
type CreateCopyInRepoParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*copy data as octet stream
	  Required: true
	  In: body
	*/
	CopyData models.InputStream
	/*The id of the copy instance.
	  Required: true
	  In: path
	*/
	CopyID string
	/*The id of the copy repository instance
	  Required: true
	  In: path
	*/
	RepoID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateCopyInRepoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		o.CopyData = r.Body

	} else {
		res = append(res, errors.Required("copyData", "body"))
	}

	rCopyID, rhkCopyID, _ := route.Params.GetOK("copyId")
	if err := o.bindCopyID(rCopyID, rhkCopyID, route.Formats); err != nil {
		res = append(res, err)
	}

	rRepoID, rhkRepoID, _ := route.Params.GetOK("repoId")
	if err := o.bindRepoID(rRepoID, rhkRepoID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateCopyInRepoParams) bindCopyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.CopyID = raw

	return nil
}

func (o *CreateCopyInRepoParams) bindRepoID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.RepoID = raw

	return nil
}
