// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package crb_web_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../work/nazgul/copyrepo/copyrepo-web-api/src/main/resources/models"
)

// RetrieveCopyOKCode is the HTTP code returned for type RetrieveCopyOK
const RetrieveCopyOKCode int = 200

/*RetrieveCopyOK Successfully retrieved copy instance data and streamed back

swagger:response retrieveCopyOK
*/
type RetrieveCopyOK struct {

	/*
	  In: Body
	*/
	Payload models.OutputStream `json:"body,omitempty"`
}

// NewRetrieveCopyOK creates RetrieveCopyOK with default headers values
func NewRetrieveCopyOK() *RetrieveCopyOK {
	return &RetrieveCopyOK{}
}

// WithPayload adds the payload to the retrieve copy o k response
func (o *RetrieveCopyOK) WithPayload(payload models.OutputStream) *RetrieveCopyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve copy o k response
func (o *RetrieveCopyOK) SetPayload(payload models.OutputStream) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveCopyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// RetrieveCopyNotFoundCode is the HTTP code returned for type RetrieveCopyNotFound
const RetrieveCopyNotFoundCode int = 404

/*RetrieveCopyNotFound Copy instance with specified copyId does not exist. If copy instance loss is permanent, client should delete this copy instance.

swagger:response retrieveCopyNotFound
*/
type RetrieveCopyNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRetrieveCopyNotFound creates RetrieveCopyNotFound with default headers values
func NewRetrieveCopyNotFound() *RetrieveCopyNotFound {
	return &RetrieveCopyNotFound{}
}

// WithPayload adds the payload to the retrieve copy not found response
func (o *RetrieveCopyNotFound) WithPayload(payload *models.Error) *RetrieveCopyNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve copy not found response
func (o *RetrieveCopyNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveCopyNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveCopyInternalServerErrorCode is the HTTP code returned for type RetrieveCopyInternalServerError
const RetrieveCopyInternalServerErrorCode int = 500

/*RetrieveCopyInternalServerError Internal error -- most likely access issue with copy-repo or with Metadata-DB

swagger:response retrieveCopyInternalServerError
*/
type RetrieveCopyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRetrieveCopyInternalServerError creates RetrieveCopyInternalServerError with default headers values
func NewRetrieveCopyInternalServerError() *RetrieveCopyInternalServerError {
	return &RetrieveCopyInternalServerError{}
}

// WithPayload adds the payload to the retrieve copy internal server error response
func (o *RetrieveCopyInternalServerError) WithPayload(payload *models.Error) *RetrieveCopyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve copy internal server error response
func (o *RetrieveCopyInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveCopyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*RetrieveCopyDefault unexpected error

swagger:response retrieveCopyDefault
*/
type RetrieveCopyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRetrieveCopyDefault creates RetrieveCopyDefault with default headers values
func NewRetrieveCopyDefault(code int) *RetrieveCopyDefault {
	if code <= 0 {
		code = 500
	}

	return &RetrieveCopyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the retrieve copy default response
func (o *RetrieveCopyDefault) WithStatusCode(code int) *RetrieveCopyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the retrieve copy default response
func (o *RetrieveCopyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the retrieve copy default response
func (o *RetrieveCopyDefault) WithPayload(payload *models.Error) *RetrieveCopyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve copy default response
func (o *RetrieveCopyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveCopyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
