// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Copy Service Broker provides a way to copy(store) data-stream associated with a copyId and retrieve data-stream for a given copyId",
    "title": "crb API",
    "version": "0.2"
  },
  "host": "localhost:8080",
  "basePath": "/crb",
  "paths": {
    "/copies": {
      "get": {
        "description": "Return copyIds from Metadata-DB",
        "tags": [
          "crb-web"
        ],
        "summary": "List all the current copy instances.",
        "operationId": "getCopyInstances",
        "parameters": [
          {
            "$ref": "#/parameters/repoIdInQuery"
          },
          {
            "$ref": "#/parameters/pageNumber"
          },
          {
            "$ref": "#/parameters/pageSize"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully listed copy instances managed by crb",
            "schema": {
              "description": "copyId is currently used to access CopyInstance.",
              "type": "array",
              "items": {
                "$ref": "#/definitions/CopyInstance"
              }
            }
          },
          "204": {
            "description": "Operation succeeded; however, currently no copies are managed by crb"
          },
          "500": {
            "description": "Internal error -- Most likely Metadata-DB could not be accessed",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/copies/{copyId}": {
      "get": {
        "description": "Return copy instance attributes",
        "tags": [
          "crb-web"
        ],
        "summary": "Get copy instance meta data",
        "operationId": "getCopyMetaData",
        "parameters": [
          {
            "$ref": "#/parameters/copyId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully returned copy instance attributes",
            "schema": {
              "$ref": "#/definitions/CopyMetaData"
            }
          },
          "404": {
            "description": "Copy instance of specified copyId does not exist",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Internal error -- Most likely Metadata-DB could not be accessed",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "description": "Store a copy instance attributes",
        "tags": [
          "crb-web"
        ],
        "summary": "Store a copy instance meta data",
        "operationId": "storeCopyMetaData",
        "parameters": [
          {
            "$ref": "#/parameters/copyId"
          },
          {
            "$ref": "#/parameters/copyMeta"
          }
        ],
        "responses": {
          "201": {
            "description": "Successfully stored copy instance attributes",
            "schema": {
              "$ref": "#/definitions/CopyInstance"
            }
          },
          "409": {
            "description": "A copy instance with the same copyId exists. Either use different copyId or delete existing copyId instance before retrying",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Internal error -- Most likely Metadata-DB could not be accessed",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "description": "Delete copy instance of specified copyId along with its metadata",
        "tags": [
          "crb-web"
        ],
        "summary": "Delete a copy data instance as well as its metadata",
        "operationId": "deleteCopy",
        "parameters": [
          {
            "$ref": "#/parameters/copyId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success - Successful operation",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "Copy instance of specified copyId does not exist",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Internal error -- Most likely Metadata-DB could not be accessed",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/copies/{copyId}/data": {
      "get": {
        "description": "Copy instance data is fetched from copy-repo and streamed back",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/octet-stream"
        ],
        "tags": [
          "crb-web-data"
        ],
        "summary": "Retrieve copy data",
        "operationId": "retrieveCopy",
        "parameters": [
          {
            "$ref": "#/parameters/copyId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved copy instance data and streamed back",
            "schema": {
              "$ref": "#/definitions/OutputStream"
            }
          },
          "404": {
            "description": "Copy instance with specified copyId does not exist. If copy instance loss is permanent, client should delete this copy instance.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Internal error -- most likely access issue with copy-repo or with Metadata-DB",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/info": {
      "get": {
        "description": "Return crb info",
        "tags": [
          "crb-web"
        ],
        "summary": "Gets CRB info",
        "operationId": "getInfo",
        "responses": {
          "200": {
            "description": "Successfully returned crb info",
            "schema": {
              "$ref": "#/definitions/Info"
            }
          },
          "500": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/repositories": {
      "get": {
        "description": "Return a list of provisioned repositories",
        "tags": [
          "crb-web"
        ],
        "summary": "Get a list of configured repositories managed by this CRB",
        "operationId": "listRepositoryInstances",
        "responses": {
          "200": {
            "description": "Successfully listed Repo instances managed by crb",
            "schema": {
              "description": "repoId is currently used to access RepositoryInstance.",
              "type": "array",
              "items": {
                "$ref": "#/definitions/RepositoryInstance"
              }
            }
          },
          "204": {
            "description": "No repositories content in Metadata-DB"
          },
          "500": {
            "description": "Internal error -- most likely Metadata-DB not accessible",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/repositories/{repoId}": {
      "get": {
        "description": "Return configuration info of a specific repository instance",
        "tags": [
          "crb-web"
        ],
        "summary": "Get repository config info of repoId instance",
        "operationId": "getRepositoryInfo",
        "parameters": [
          {
            "$ref": "#/parameters/repoId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/RepositoryInfo"
            }
          },
          "400": {
            "description": "Bad Request - malformed request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "404": {
            "description": "Repository instance of specified repoId does not exist",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Internal error -- most likely Metadata-DB not accessible",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "description": "Update (or create if not present) repository config info.",
        "tags": [
          "crb-web"
        ],
        "summary": "Update (or create if not present) repository info of specified repoId.",
        "operationId": "updateRepositoryInfo",
        "parameters": [
          {
            "$ref": "#/parameters/repoId"
          },
          {
            "$ref": "#/parameters/repoInfo"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully updated a repo info in Metadata-DB",
            "schema": {
              "$ref": "#/definitions/RepositoryInstance"
            }
          },
          "500": {
            "description": "Internal error - Most likely Metadata-DB not accessible",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "description": "Store repository configuration info.",
        "tags": [
          "crb-web"
        ],
        "summary": "Store repository info of specified repoId.",
        "operationId": "storeRepositoryInfo",
        "parameters": [
          {
            "$ref": "#/parameters/repoId"
          },
          {
            "$ref": "#/parameters/repoInfo"
          }
        ],
        "responses": {
          "201": {
            "description": "Successfully created a repo info in Metadata-DB",
            "schema": {
              "$ref": "#/definitions/RepositoryInstance"
            }
          },
          "409": {
            "description": "A repository instance with the same repoId exists. Either use different repoId or delete existing repoId instance before retrying",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Internal error - Most likely Metadata-DB not accessible",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a repository instance of specified repoId. Copy data in that repository is not deleted; however copy data will not be accessible after deleting repository instance",
        "tags": [
          "crb-web"
        ],
        "summary": "Delete a repository instance.",
        "operationId": "deleteRepository",
        "parameters": [
          {
            "$ref": "#/parameters/repoId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success - Successful operation",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "Repository instance of specified repoId does not exist",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Internal error -- Most likely Metadata-DB could not be accessed",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/repositories/{repoId}/copies/{copyId}/data": {
      "post": {
        "description": "Store copy instance data in the specified repo and create a Metadata-DB entry for this copy",
        "consumes": [
          "application/octet-stream"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "crb-web-data"
        ],
        "summary": "Create copy -- store copy data",
        "operationId": "createCopyInRepo",
        "parameters": [
          {
            "$ref": "#/parameters/repoId"
          },
          {
            "$ref": "#/parameters/copyId"
          },
          {
            "$ref": "#/parameters/copyData"
          }
        ],
        "responses": {
          "201": {
            "description": "Successfully created a copy of the data and an entry in the Metadata-DB",
            "schema": {
              "description": "Copy URL - http://\u003ccrb-endpoint\u003e/copies/\u003ccopyId\u003e",
              "type": "string"
            }
          },
          "404": {
            "description": "Repository repoId instance is not configured",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "409": {
            "description": "A copy instance with the same copyId exists. Either use different copyId or delete existing copyId instance before retrying",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "Internal error. Data could not be copied to copy-repo or copy instance metadata could not be created. If copy instance metadata can't be created, copy instance will be deleted",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/repositories/{repoId}/stats": {
      "get": {
        "description": "Return metadata associated with the repository with repoId",
        "tags": [
          "crb-web"
        ],
        "summary": "Get stats of the repoId such as used/available space etc.",
        "operationId": "getRepositoryStats",
        "parameters": [
          {
            "$ref": "#/parameters/repoId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/RepositoryStats"
            }
          },
          "204": {
            "description": "No repoId in Metadata-DB"
          },
          "500": {
            "description": "Internal error -- most likely Metadata-DB not accessible",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CopyInstance": {
      "description": "copyURL",
      "type": "object",
      "properties": {
        "copyURL": {
          "type": "string"
        }
      },
      "example": {
        "copyURL": "http://\u003ccrb-endpoint\u003e/copies/\u003ccopyId\u003e"
      }
    },
    "CopyMetaData": {
      "type": "object",
      "properties": {
        "copyAdditionalInfo": {
          "type": "object",
          "additionalProperties": {
            "description": "Can include arbitrary string to string mappings of key-value pairs about the copy instance such as copySourceSizeInBytes, platform org \u0026 space, DSB used for copy, application using this data, etc. CRB server can also fill additional properties such as copyTargetSizeInByte, copySizeReductionPercentage etc. CRB client will persist this information for a later retrieval by CRB client.",
            "type": "string"
          }
        },
        "copyDataURL": {
          "description": "Link to the location of the copy data",
          "type": "string"
        },
        "copyId": {
          "description": "Unique copy Id",
          "type": "string"
        },
        "copyTimeStamp": {
          "description": "Time when copy is initiated \u0026 completed in UTC",
          "type": "string",
          "format": "date-time"
        },
        "protocol": {
          "description": "Protocol used to make this copy",
          "type": "string"
        },
        "protocolVersion": {
          "description": "version of protocol used to make this copy",
          "type": "string"
        },
        "repoId": {
          "description": "Unique Copy Repository Id",
          "type": "string"
        }
      },
      "example": {
        "copyAdditionalInfo": "{copySourceSizeInBytes: 1018518509, org:cndp, space:saruman, dsb:mysql-dsb, app:hackathon, copyTargeSizeInBytes: 123456789, copySizeReductionPercentage: 825}",
        "copyDataURL": "http://\u003ccrb-endpoint\u003e/copies/\u003ccopyId\u003e/data",
        "copyId": "f4d1912a-2b87-11e7-93ae-92361f002671",
        "copyTimeStamp": "2017-03-09T13:06:08.260Z",
        "protocol": "nfs",
        "protocolVersion": "4.1"
      }
    },
    "Info": {
      "type": "object",
      "properties": {
        "build": {
          "description": "crb microservice software build number",
          "type": "string"
        },
        "name": {
          "description": "crb service name",
          "type": "string"
        },
        "repoType": {
          "description": "crb managed repositories type",
          "type": "string"
        },
        "version": {
          "description": "crb microservice version",
          "type": "string"
        }
      },
      "example": {
        "build": "0.1.0.116",
        "name": "crb",
        "repoType": "file",
        "version": "0.1"
      }
    },
    "InputStream": {
      "description": "Octet Stream",
      "type": "string",
      "format": "binary"
    },
    "OutputStream": {
      "description": "Octet Stream",
      "type": "string",
      "format": "binary"
    },
    "RepositoryInfo": {
      "type": "object",
      "properties": {
        "id": {
          "description": "Globally unique key for a configured copy repository. This id is provided to crb and later used to specify which repository copy should be saved.",
          "type": "string"
        },
        "name": {
          "description": "(optional) User friendly name configured for copy repository",
          "type": "string"
        },
        "repoAdditionalInfo": {
          "type": "object",
          "additionalProperties": {
            "description": "Can include arbitrary string to string mappings of key-value pairs about the copy repo",
            "type": "string"
          }
        },
        "repoSupportedProtocols": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/supportedProtocol"
          }
        }
      },
      "example": {
        "id": "247b0da2-2b88-11e7-93ae-92361f002671",
        "name": "test-dev-file-server",
        "repoAdditionalInfo": "{fileServer:Dell Precision Tower}",
        "repoSupportedProtocols": "[{ protocol:nfs, version:4.1, endpoint:{addr: 192.168.10.10, endpointAdditionalInfo{location:Hopkinton}}, credentials:{user:xyz, password:abc, credentialsAdditionalInfo:{key:MY_KEY, secret:MY_SECRET}}, copyLocation:{path:/var/lib/crb/, copyLocationAdditionalInfo:{mountpoint:/var}}, repoAdditionalInfo: {} }]"
      }
    },
    "RepositoryInstance": {
      "description": "RepoURLs",
      "type": "object",
      "properties": {
        "repoId": {
          "type": "string"
        },
        "repoURL": {
          "type": "string"
        }
      },
      "example": {
        "repoId": "arbitrary-repo-id",
        "repoURL": "http://\u003ccrb-endpoint\u003e/repositories/\u003crepoId\u003e"
      }
    },
    "RepositoryStats": {
      "type": "object",
      "properties": {
        "availableCapacityInBytes": {
          "description": "total capacity available in bytes",
          "type": "integer",
          "format": "int64"
        },
        "numberOfCopiesStored": {
          "type": "integer",
          "format": "int32"
        },
        "totalCapacityInBytes": {
          "description": "total capacity in bytes",
          "type": "integer",
          "format": "int64"
        },
        "usedCapacityInBytes": {
          "description": "total capacity already used in bytes",
          "type": "integer",
          "format": "int64"
        }
      },
      "example": {
        "availableCapacityInBytes": 33632358400,
        "numberOfCopiesStored": 1036,
        "totalCapacityInBytes": 1073741824000,
        "usedCapacityInBytes": 73741824000
      }
    },
    "error": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      },
      "example": {
        "code": "other than 500 that implementation may support -  e.g. 599",
        "message": "message for the error code - e.g., filesystem connection timeout"
      }
    },
    "supportedProtocol": {
      "type": "object",
      "required": [
        "protocol",
        "version",
        "endpoint",
        "credentials"
      ],
      "properties": {
        "copyLocation": {
          "type": "object",
          "properties": {
            "copyLocationAdditionalInfo": {
              "type": "object",
              "additionalProperties": {
                "description": "Can include arbitrary string to string mappings of key-value pairs to specify a location within a container.",
                "type": "string"
              }
            },
            "path": {
              "description": "Optional input of copies' location.  Could be absolute path on a mounted filesystem. Appropriate default should be used (such as /var/lib/crb).",
              "type": "string"
            }
          }
        },
        "credentials": {
          "type": "object",
          "properties": {
            "credentialsAdditionalInfo": {
              "type": "object",
              "additionalProperties": {
                "description": "Can include arbitrary string to string mappings of key-value pairs (such as account key info) that could be required to gain access to the endpoint.",
                "type": "string"
              }
            },
            "password": {
              "type": "string"
            },
            "user": {
              "type": "string"
            }
          }
        },
        "endpoint": {
          "type": "object",
          "properties": {
            "addr": {
              "description": "basic IP addr of dns name",
              "type": "string"
            },
            "endPointAdditionalInfo": {
              "type": "object",
              "additionalProperties": {
                "description": "Can include arbitrary string to string mappings of key-value pairs to describe endpoint",
                "type": "string"
              }
            }
          }
        },
        "protocol": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "copyData": {
      "description": "copy data as octet stream",
      "name": "copyData",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/InputStream"
      }
    },
    "copyId": {
      "type": "string",
      "description": "The id of the copy instance.",
      "name": "copyId",
      "in": "path",
      "required": true
    },
    "copyMeta": {
      "description": "copy metadata",
      "name": "copyMeta",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/CopyMetaData"
      }
    },
    "pageNumber": {
      "type": "integer",
      "format": "int32",
      "description": "page number of paginated list. e.g. copies list",
      "name": "pageNumber",
      "in": "query"
    },
    "pageSize": {
      "type": "integer",
      "format": "int32",
      "description": "page size of paginated list. e.g. copies list",
      "name": "pageSize",
      "in": "query"
    },
    "repoId": {
      "type": "string",
      "description": "The id of the copy repository instance",
      "name": "repoId",
      "in": "path",
      "required": true
    },
    "repoIdInQuery": {
      "type": "string",
      "description": "The id of the copy repository instance",
      "name": "repoIdInQuery",
      "in": "query"
    },
    "repoInfo": {
      "description": "repository access info",
      "name": "repoInfo",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/RepositoryInfo"
      }
    }
  },
  "tags": [
    {
      "name": "crb-web"
    }
  ]
}`))
}
