// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// CopyMetaData copy meta data
// swagger:model CopyMetaData
type CopyMetaData struct {

	// copy additional info
	CopyAdditionalInfo map[string]string `json:"copyAdditionalInfo,omitempty"`

	// Link to the location of the copy data
	CopyDataURL string `json:"copyDataURL,omitempty"`

	// Unique copy Id
	CopyID string `json:"copyId,omitempty"`

	// Time when copy is initiated & completed in UTC
	CopyTimeStamp strfmt.DateTime `json:"copyTimeStamp,omitempty"`

	// Protocol used to make this copy
	Protocol string `json:"protocol,omitempty"`

	// version of protocol used to make this copy
	ProtocolVersion string `json:"protocolVersion,omitempty"`

	// Unique Copy Repository Id
	RepoID string `json:"repoId,omitempty"`
}

// Validate validates this copy meta data
func (m *CopyMetaData) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
