// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Info info
// swagger:model Info
type Info struct {

	// crb microservice software build number
	Build string `json:"build,omitempty"`

	// crb service name
	Name string `json:"name,omitempty"`

	// crb managed repositories type
	RepoType string `json:"repoType,omitempty"`

	// crb microservice version
	Version string `json:"version,omitempty"`
}

// Validate validates this info
func (m *Info) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
