// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package models

import "io"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// OutputStream Octet Stream
// swagger:model OutputStream
type OutputStream io.ReadCloser
