// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// RepositoryInstance RepoURLs
// swagger:model RepositoryInstance
type RepositoryInstance struct {

	// repo Id
	RepoID string `json:"repoId,omitempty"`

	// repo URL
	RepoURL string `json:"repoURL,omitempty"`
}

// Validate validates this repository instance
func (m *RepositoryInstance) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
