// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// RepositoryStats repository stats
// swagger:model RepositoryStats
type RepositoryStats struct {

	// total capacity available in bytes
	AvailableCapacityInBytes int64 `json:"availableCapacityInBytes,omitempty"`

	// number of copies stored
	NumberOfCopiesStored int32 `json:"numberOfCopiesStored,omitempty"`

	// total capacity in bytes
	TotalCapacityInBytes int64 `json:"totalCapacityInBytes,omitempty"`

	// total capacity already used in bytes
	UsedCapacityInBytes int64 `json:"usedCapacityInBytes,omitempty"`
}

// Validate validates this repository stats
func (m *RepositoryStats) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
