// Copyright (c) [2017] Dell Inc. or its subsidiaries. All Rights Reserved.
import Reflux from 'reflux';

var Actions = Reflux.createActions([
    "userClickOnHamburger",
    "userClickAppPreview",
    "userClickOnCard",
    "userClickOnNextWizard",
    "userClickOnNextCompleteWizard",
    "userClickOnBackWizard",
    "userClickOnInfrastructure",
    "userClickOnBusinessSettingsPlan",
    "userClickOnCopyHistoryRangeFilter",
    "userClickOnCopyHistoryPrevBtn",
    "userClickOnCopyHistoryNextBtn",
    "userClickOnSiteSetup",
    "userClickOnCopyHistoryBackup",
    "hideCopyHistoryRestoreTooltip",
    "initializeCopyHistorySettings",
    "userClickOnRePurposeCopy",
    "userClickOnTooltipRestore",
    "userClickOnRestoreFromPopup",
    "userClickOnCloseRetorePopup",
    "showLoadingGif",
    "hideLoadingGif",
    "showComponentLoadingGif",
    "hideComponentLoadingGif",
    "browserDetectionRedirect",
    "blockBrowserByName",
  	"goToDashboard",
    "navigateToDashboard",
    "goToMainScreen",
    "goToWizard",
    "showErrorDialog",
    "hideErrorDialog",
    "initializeWizardSettings",
    "setAppInstanceName",
    "getAllAppInstances",
    "setAppInstance",
    "setAppInstanceNameFromDialog",
    "getCurrentAppInstance",
    "setHashLocation",
  	"navigateByName",
  	"setLeftMenuInitialState",
  	"userClickOnLeftMenuAppInstance",
  	"setWizardCurrentStep",
  	"removeCopyHistoryErrorMsg",
  	"setMainPaneClass",
  	"showStatisticsPieLoadingGif",
  	"hideStatisticsPieLoadingGif",
  	"createAppCopy",
    "editAppInstanceName",
    "hideEditAppInstanceName",
  	"setLoginUsername",
  	"setLoginPassword",
  	"login",
  	"logout",
    "setSelectedApp",
  	"toogleSettingsTooltip",
  	"toggleSettingsTooltipModes",
    "closeSettingsTooltipModes",
    "closeSettingsTooltip",
    "openLeftMenu",
    "closeLeftMenu"
]);

export default Actions;
